---
 
- name: Add Repositories folder to Remote Machines
  become: yes
  synchronize: 
    src: /var/www/html/repos
    dest: /var/www/html
  delegate_to: 127.0.0.1


- name: Add local.repo to Remote Machines
  become: yes
  synchronize:
    src: /etc/yum.repos.d/local.repo 
    dest: /etc/yum.repos.d/local.repo
  delegate_to: 127.0.0.1
...
