--- 
- name: Install Epel Repositories
  become: yes
  yum: 
    name: "{{ epel_repo_url }}" 
    state: installed

- name: Install Remi Repositories
  become: yes
  yum:
    name: "{{ remi_repo_url }}"
    state: installed

- name: Enable remi-PHP
  shell: dnf -y module enable php:remi-7.4

- name: Install PHP
  become: yes
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
      - php
      - php-pear
      - php-cgi
      - php-common
      - php-mbstring
      - php-snmp
      - php-gd
      - php-pecl-mysql
      - php-xml
      - php-mysql
      - php-gettext
      - php-bcmath
